### ISSUE TITLE
Any good example ?

### ISSUE THREAD

**Issue by shinji62** [CAFxX/gcnotifier#1]

**Comment by shenwei356** [comment]
yes, could you please give some examples? @CAFxX

**Comment by CAFxX** [comment]
I added an example of a time-based buffering writer: https://github.com/CAFxX/gcnotifier/blob/37a761ed5889e8ad2295d25e111a5b2b6dba9d59/gcnotifier_test.go#L42-L89

**Comment by CAFxX** [comment]
I'll close this for now, let me know if you think the example is unclear or if more examples are needed.
